### ISSUE TITLE
Issue with downloading some maps

### ISSUE THREAD

**Issue by Nerbz** [Jenjen1324/cobaltvault.no#5]
When I try to download some maps, I just get this:
http://gyazo.com/d4971197047f3f5d7984162cad53303e
When I refresh it, or try to download again, it does the same thing. Some downloads work, some don't. Help?

**Comment by Janeator** [comment]
Does it happen in some specific works? Do the downloads that work always work, and the ones that fail always fail? If so, which are each, that you have tested?

**Comment by Jenjen1324** [comment]
The image link seems broken to me. Could you please reupload it to imgur or a similar image hosting site?
Also could you provide the projects you are trying to download?

**Comment by Nerbz** [comment]
One of the maps I tried to download was called "Underworld" and "Infection" I think.

**Comment by Jenjen1324** [comment]
If you are trying to download http://www.cobaltvault.no/project/underworld that won't work because the author didn't upload any files to the project. I'll add something that prevents you from downloading such projects.
